version: "3.7"
services:
  fatura_any:
    image: marcelogbjunior/importa_xml_magalu:0.0.1
    network_mode: "host"
    container_name: importa_xml_magalu
    environment:
      - DB_HOST=
      - DB_PORT=3306
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DATEPRIOR=
    ports:
      - 3014
    volumes:
      - ".:/web"
    restart: always